
**Dataset:**
Breast Cancer dataset available in `sklearn`.

## 1. Import Required Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

## 2. Load the Breast Cancer Dataset

In [3]:
data = load_breast_cancer()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="target")

print("Dataset shape:", X.shape)
print("Target shape:", y.shape)

X.head()

Dataset shape: (569, 30)
Target shape: (569,)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

## 3. Check Missing Values

We check the dataset for missing values before training the models.

In [4]:
print("Total missing values:", X.isnull().sum().sum())
print("\nMissing values in each column:")
print(X.isnull().sum())

Total missing values: 0

Missing values in each column:
mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
dtype: int64

### Preprocessing Explanation

- The dataset is checked for missing values.
- `SimpleImputer(strategy="median")` is included in the pipelines to handle any missing numerical values.
- `StandardScaler()` is used for Logistic Regression, SVM, and k-NN because these algorithms are affected by feature scale.
- Decision Tree and Random Forest do not require feature scaling.

## 4. Split the Dataset into Training and Testing Data

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

Training data: (455, 30)
Testing data: (114, 30)

## 5. Logistic Regression

**How it works:** Logistic Regression predicts the probability of an observation belonging to a class.

**Why suitable:** The Breast Cancer dataset is a binary classification problem, so Logistic Regression is suitable.

In [6]:
logistic_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=5000))
])

logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)

print("Logistic Regression Accuracy:",
      accuracy_score(y_test, y_pred_logistic))

Logistic Regression Accuracy: 0.9824561403508771

## 6. Decision Tree Classifier

**How it works:** A Decision Tree repeatedly splits the data based on feature values to make a prediction.

**Why suitable:** It can model nonlinear relationships and does not require feature scaling.

In [7]:
decision_tree = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", DecisionTreeClassifier(random_state=42))
])

decision_tree.fit(X_train, y_train)
y_pred_tree = decision_tree.predict(X_test)

print("Decision Tree Accuracy:",
      accuracy_score(y_test, y_pred_tree))

Decision Tree Accuracy: 0.9122807017543859

## 7. Random Forest Classifier

**How it works:** Random Forest combines predictions from multiple decision trees.

**Why suitable:** It can handle many numerical features and capture complex relationships.

In [8]:
random_forest = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("model", RandomForestClassifier(
        n_estimators=100,
        random_state=42
    ))
])

random_forest.fit(X_train, y_train)
y_pred_rf = random_forest.predict(X_test)

print("Random Forest Accuracy:",
      accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.956140350877193

## 8. Support Vector Machine (SVM)

**How it works:** SVM finds a decision boundary that separates classes while maximizing the margin between them.

**Why suitable:** SVM can work effectively with numerical features and complex class boundaries. Feature scaling is important for SVM.

In [9]:
svm_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", SVC())
])

svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)

print("SVM Accuracy:",
      accuracy_score(y_test, y_pred_svm))

SVM Accuracy: 0.9824561403508771

## 9. k-Nearest Neighbors (k-NN)

**How it works:** k-NN classifies a new observation based on the classes of its nearest neighboring observations.

**Why suitable:** The dataset contains numerical features, and k-NN can use distances between observations. Feature scaling is important.

In [10]:
knn_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", KNeighborsClassifier(n_neighbors=5))
])

knn_model.fit(X_train, y_train)
y_pred_knn = knn_model.predict(X_test)

print("k-NN Accuracy:",
      accuracy_score(y_test, y_pred_knn))

k-NN Accuracy: 0.956140350877193

## 10. Model Comparison

In [11]:
models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_tree,
    "Random Forest": random_forest,
    "SVM": svm_model,
    "k-NN": knn_model
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    })

results_df = pd.DataFrame(results)

results_df

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.982456   0.986111  0.986111  0.986111
1        Decision Tree  0.912281   0.955882  0.902778  0.928571
2        Random Forest  0.956140   0.958904  0.972222  0.965517
3                  SVM  0.982456   0.986111  0.986111  0.986111
4                 k-NN  0.956140   0.958904  0.972222  0.965517

## 11. Identify Highest and Lowest Accuracy

The following code identifies the models with the highest and lowest test accuracy for the selected train-test split.

In [12]:
best_model = results_df.loc[results_df["Accuracy"].idxmax()]
worst_model = results_df.loc[results_df["Accuracy"].idxmin()]

print("Highest Accuracy:")
print(best_model)

print("\nLowest Accuracy:")
print(worst_model)

Highest Accuracy:
Model        Logistic Regression
Accuracy                0.982456
Precision               0.986111
Recall                  0.986111
F1 Score                0.986111
Name: 0, dtype: object

Lowest Accuracy:
Model        Decision Tree
Accuracy          0.912281
Precision         0.955882
Recall            0.902778
F1 Score          0.928571
Name: 1, dtype: object

## 12. Conclusion

Five supervised classification algorithms were implemented on the Breast Cancer dataset: Logistic Regression, Decision Tree, Random Forest, SVM, and k-NN.

The dataset was checked for missing values and preprocessing was performed using median imputation and feature scaling where required. The models were evaluated using accuracy, precision, recall, and F1-score.

The final best and worst performers are determined directly from the test-set results above. Results can vary depending on the train-test split and model settings.