Numpy and Pandas 
1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 
matrix. (Score:1) 
2. Create a numpy array containing the numbers from 1 to 20, and then extract the 
elements between the 5th and 15th index. (Score:1) 
3. How to compute the mean, median, and standard deviation of a numpy array?Use the 
array you created above (Score 1) 
4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of 
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)  
5. Create a dataframe with the following columns: name, age, and gender. The dataframe 
should have 10 rows of data. (Score: 2) 
1) Add a new column to the data frame created in question 1, called occupation. 
The values for this column should be Programmer, Manager, and Analyst, 
corresponding to the rows in the dataframe. (Score: 1) 
2) Select the rows of the dataframe where the age is greater than or equal to 30. 
(Score: 1) 
3) Convert this dataframe to a CSV file and read that CSV file, and finally display 
the contents. (Score: 1)

1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 
matrix. (Score:1)

In [2]:
import numpy as np
import pandas as pd

In [5]:
arr=np.array(range(1,11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr=np.array(range(1,11)).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

2. Create a numpy array containing the numbers from 1 to 20, and then extract the 
elements between the 5th and 15th index. (Score:1)

In [8]:
arr1=np.array(range(1,21))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [11]:
arr1=np.array(range(1,21))
arr1[5:16]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

3. How to compute the mean, median, and standard deviation of a numpy array?Use the 
array you created above (Score 1)

In [20]:
arr1=np.array(range(1,21)).mean()
arr1

np.float64(10.5)

In [15]:
arr1=np.array(range(1,21))
print(np.median(arr1))

10.5

In [19]:
arr1=np.array(range(1,21))
print(np.std(arr1))

5.766281297335398

4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of 
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [23]:
arr2=np.array([[[10,20,30,40],[50,60,70,80],[90,100,110,120]]]).reshape(3,4)
arr2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [25]:
arr3=np.array([1,2,3,4]).reshape(4)
arr3

array([1, 2, 3, 4])

In [27]:
print(arr2-arr3)

[[  9  18  27  36]
 [ 49  58  67  76]
 [ 89  98 107 116]]

5. Create a dataframe with the following columns: name, age, and gender. The dataframe 
should have 10 rows of data. (Score: 2) 
1) Add a new column to the data frame created in question 1, called occupation. 
The values for this column should be Programmer, Manager, and Analyst, 
corresponding to the rows in the dataframe. (Score: 1) 
2) Select the rows of the dataframe where the age is greater than or equal to 30. 
(Score: 1) 
3) Convert this dataframe to a CSV file and read that CSV file, and finally display 
the contents. (Score: 1)

In [30]:
data={
    "name":["arun","keerthi","varun","miya","krishna","rama","seetha","anju","jiya","lia"],
    "age":[20,19,18,22,23,34,16,45,8,24],
    "sex":["M","F","M","F","M","M","F","F","F","F"]
}
df=pd.DataFrame(data)
df

      name  age sex
0     arun   20   M
1  keerthi   19   F
2    varun   18   M
3     miya   22   F
4  krishna   23   M
5     rama   34   M
6   seetha   16   F
7     anju   45   F
8     jiya    8   F
9      lia   24   F

1) Add a new column to the data frame created in question 1, called occupation. 
The values for this column should be Programmer, Manager, and Analyst, 
corresponding to the rows in the dataframe. (Score: 1)

In [31]:
df["occupation"]=["Programmer","Manager"," Analyst","Programmer","Manager"," Analyst","Programmer","Manager","Analyst","Programmer"]
df

      name  age sex  occupation
0     arun   20   M  Programmer
1  keerthi   19   F     Manager
2    varun   18   M     Analyst
3     miya   22   F  Programmer
4  krishna   23   M     Manager
5     rama   34   M     Analyst
6   seetha   16   F  Programmer
7     anju   45   F     Manager
8     jiya    8   F     Analyst
9      lia   24   F  Programmer

2) Select the rows of the dataframe where the age is greater than or equal to 30. 
(Score: 1)

In [35]:
df[df["age"]>=30]

   name  age sex occupation
5  rama   34   M    Analyst
7  anju   45   F    Manager

3) Convert this dataframe to a CSV file and read that CSV file, and finally display 
the contents. (Score: 1)

In [36]:
df.to_csv("data.csv",index=False)
new_df=pd.read_csv("data.csv")
print(new_df)

      name  age sex  occupation
0     arun   20   M  Programmer
1  keerthi   19   F     Manager
2    varun   18   M     Analyst
3     miya   22   F  Programmer
4  krishna   23   M     Manager
5     rama   34   M     Analyst
6   seetha   16   F  Programmer
7     anju   45   F     Manager
8     jiya    8   F     Analyst
9      lia   24   F  Programmer